language: python
python:
  - '3.5'
cache: pip

install:
  - pip install -r requirements.txt
  - wget https://sourceforge.net/projects/bbmap/files/BBMap_37.68.tar.gz
  - tar xf BBMap_37.68.tar.gz
  - export PATH=$PATH:$PWD/bbmap/
  - sudo apt install bedtools
  - wget https://github.com/samtools/samtools/releases/download/1.6/samtools-1.6.tar.bz2 && tar xf samtools-1.6.tar.bz2
  - pushd samtools-1.6 && ./configure --prefix /usr && make && sudo make install && popd
  - wget https://github.com/refresh-bio/KMC/releases/download/v3.0.0/KMC3.linux.tar.gz && tar xf KMC3.linux.tar.gz
  - export PATH=$PATH:$PWD
  - sudo apt install ncbi-blast+
branches:
  only:
    - master

script:
  - pytest tests/test_sigseekr.py
