site_name: SigSeekr
site_url: https://olc-bioinformatics.github.io/SigSeekr/
site_description: SigSeekr pipeline for generating signature sequences for one or more genomes.
repo_url: https://github.com/OLC-Bioinformatics/SigSeekr
theme: flatly

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'
